url: "https://gabrielmarin97.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/home" # the subpath of your site, e.g. /blog
title: "Gabriel Marin Muñoz" # the name of your site, e.g. ACME Corp.
description: "Graduate Research Associate, Arizona State University"
