menu:
- {name: 'Photos', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Macroeconomic Policy: Fiscal, Monetary and Finance', url: 'vector-calculus'}


social:
- {icon: 'github', link: 'https://github.com/gabrielmarin97'}
- {icon: 'twitter', link: 'https://twitter.com/gabrielmarin97'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/gabrielmarin97/'}

contact:
- {name: 'Gabriel Marin', title: 'Research Fellow', department: 'Research Department', institution: 'Inter-American Development Bank', institution_address: '1300 New York Avenue NW, Washington, D.C.', email: 'gmarinmunoz@iadb.org', office: '1007SE', image: 'assets/img/IDB_afternoon.jpeg'}
