menu:
- {name: 'Photos', url: '/photos'}
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/teaching'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

photos:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

teaching:
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}

social:
- {icon: 'github', link: 'https://github.com/gabrielmarin97'}
- {icon: 'twitter', link: 'https://twitter.com/gabrielmarin97'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/gabrielmarin97/'}

contact:
- {name: 'Gabriel Marin', title: 'Research Fellow', department: 'Research Department', institution: 'Inter-American Development Bank', institution_address: '1300 New York Avenue NW, Washington, D.C.', email: 'gmarinmunoz@iadb.org', office: '1007SE', image: 'assets/img/IDB_afternoon.jpeg'}
