menu:
- {name: 'Photos', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Calm', date: 'July 2023', image: 'assets/img/kayak.jpg'}
- {name: 'Renewal', date: 'June 2023', image: 'assets/img/new_apt.jpeg'}
- {name: 'Concrete Jungle', date: 'May 2023', image: 'assets/img/concrete_jungle.jpeg'}
- {name: 'Blossom', date: 'March 2023', image: 'assets/img/blossom.jpeg'}
- {name: 'Memories', date: 'February 2023', image: 'assets/img/memories.jpeg'}
- {name: 'Pepper (1 year)', date: 'December 2022', image: 'assets/img/pepper.jpg'}
- {name: 'Mia (4 years)', date: 'December 2022', image: 'assets/img/side_eye_mia.jpeg'}
- {name: 'Family Restaurant', date: 'December 2022', image: 'assets/img/family_restaurant.jpeg'}
- {name: 'Christmas Ginger (13 years)', date: 'December 2022', image: 'assets/img/christmas_ginger.jpeg'}
- {name: 'Austin Bridge', date: 'December 2022', image: 'assets/img/bridge_austin.jpeg'}
- {name: 'Two Paths', date: 'November 2022', image: 'assets/img/where_to_go.jpeg'}
- {name: 'Hike', date: 'November 2022', image: 'assets/img/hike_gtown.jpeg'}
- {name: 'New Beginnings', date: 'October 2021', image: 'assets/img/new_beginnings.jpeg'}
- {name: 'Porfirio (n.d.)', date: 'September 2021', image: 'assets/img/porfirio.jpeg'}
- {name: 'Transformation', date: 'September 2021', image: 'assets/img/transformation.jpeg'}
- {name: 'Peace', date: 'June 2021', image: 'assets/img/peace.jpeg'}
- {name: 'Beyond', date: 'June 2021', image: 'assets/img/beyond.jpeg'}
- {name: 'Asymmetry', date: 'June 2021', image: 'assets/img/asymmetry.jpeg'}

courses:
- {name: 'Applied International Macroeconomics', url: 'aim'}
- {name: 'Macroeconomic Policy: Fiscal, Monetary and Finance', url: 'vector-calculus'}



social:
- {icon: 'github', link: 'https://github.com/gabrielmarin97'}
- {icon: 'twitter', link: 'https://twitter.com/gabrielmarin97'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/gabrielmarin97/'}

contact:
- {name: 'Gabriel Marin', title: 'Graduate Research Associate', department: 'Economics Department', institution: 'Arizona State University', institution_address: '501 E Orange St., Tempe, AZ 85281', email: 'gmarinmu@asu.edu', office: 'TBD', image: 'assets/img/ASU_cactus.jpeg'}
